name: pta
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.11
  - jupyter
  - numpy
  - scipy
  - pandas
  - matplotlib
  - corner
  - tqdm
  - healpy
  - astropy
  - psrqpy
  - libstempo
  - enterprise-pulsar
  - enterprise_extensions
  - dynesty
  - ptmcmcsampler
  - setuptools>=70.0.0
  - netcdf4
  - pyyaml
  - snakemake
  - pip
  - pip:
    - typer>=0.9.0
    - colorlog
    - -e ../lib/pta_catalog
    - -e ..